package hibernate.model;
// Generated 20 déc. 2015 18:41:22 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * TableUtilisateurs generated by hbm2java
 */
import org.hibernate.annotations.DynamicUpdate;
@DynamicUpdate
public class TableUtilisateurs implements java.io.Serializable {

	private BigDecimal iduser;
	private String useruid;
	private BigDecimal idtypecompte;
	private Date datecreation;

	public TableUtilisateurs() {
	}

	public TableUtilisateurs(BigDecimal iduser, String useruid, BigDecimal idtypecompte) {
		this.iduser = iduser;
		this.useruid = useruid;
		this.idtypecompte = idtypecompte;
	}

	public TableUtilisateurs(BigDecimal iduser, String useruid, BigDecimal idtypecompte, Date datecreation) {
		this.iduser = iduser;
		this.useruid = useruid;
		this.idtypecompte = idtypecompte;
		this.datecreation = datecreation;
	}

	public BigDecimal getIduser() {
		return this.iduser;
	}

	public void setIduser(BigDecimal iduser) {
		this.iduser = iduser;
	}

	public String getUseruid() {
		return this.useruid;
	}

	public void setUseruid(String useruid) {
		this.useruid = useruid;
	}

	public BigDecimal getIdtypecompte() {
		return this.idtypecompte;
	}

	public void setIdtypecompte(BigDecimal idtypecompte) {
		this.idtypecompte = idtypecompte;
	}

	public Date getDatecreation() {
		return this.datecreation;
	}

	public void setDatecreation(Date datecreation) {
		this.datecreation = datecreation;
	}

}
