package hibernate.model;
// Generated 5 janv. 2016 11:25:45 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * TableNews generated by hbm2java
 */
public class TableNews implements java.io.Serializable {

	private BigDecimal idnews;
	private String titre;
	private String body;
	private Date datepublication;
	private String nomannonceur;

	public TableNews() {
	}

	public TableNews(BigDecimal idnews, String titre, String body) {
		this.idnews = idnews;
		this.titre = titre;
		this.body = body;
	}

	public TableNews(BigDecimal idnews, String titre, String body, Date datepublication, String nomannonceur) {
		this.idnews = idnews;
		this.titre = titre;
		this.body = body;
		this.datepublication = datepublication;
		this.nomannonceur = nomannonceur;
	}

	public BigDecimal getIdnews() {
		return this.idnews;
	}

	public void setIdnews(BigDecimal idnews) {
		this.idnews = idnews;
	}

	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	public String getBody() {
		return this.body;
	}

	public void setBody(String body) {
		this.body = body;
	}

	public Date getDatepublication() {
		return this.datepublication;
	}

	public void setDatepublication(Date datepublication) {
		this.datepublication = datepublication;
	}

	public String getNomannonceur() {
		return this.nomannonceur;
	}

	public void setNomannonceur(String nomannonceur) {
		this.nomannonceur = nomannonceur;
	}

}
