package hibernate.model;
// Generated 20 déc. 2015 18:41:22 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;

/**
 * TableAdmin generated by hbm2java
 */
import org.hibernate.annotations.DynamicUpdate;
@DynamicUpdate
public class TableAdmin implements java.io.Serializable {

	private BigDecimal idadmin;
	private BigDecimal iduser;
	private String nom;
	private String prenom;
	private String email;
	private String numero;

	public TableAdmin() {
	}

	public TableAdmin(BigDecimal idadmin, BigDecimal iduser, String nom, String prenom, String email) {
		this.idadmin = idadmin;
		this.iduser = iduser;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
	}

	public TableAdmin(BigDecimal idadmin, BigDecimal iduser, String nom, String prenom, String email, String numero) {
		this.idadmin = idadmin;
		this.iduser = iduser;
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.numero = numero;
	}

	public BigDecimal getIdadmin() {
		return this.idadmin;
	}

	public void setIdadmin(BigDecimal idadmin) {
		this.idadmin = idadmin;
	}

	public BigDecimal getIduser() {
		return this.iduser;
	}

	public void setIduser(BigDecimal iduser) {
		this.iduser = iduser;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

}
