package hibernate.model;
// Generated 5 janv. 2016 11:25:45 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * TableEvenements generated by hbm2java
 */
public class TableEvenements implements java.io.Serializable {

	private BigDecimal idevent;
	private String nomevenement;
	private Date datedebut;
	private Date datefin;

	public TableEvenements() {
	}

	public TableEvenements(BigDecimal idevent, String nomevenement) {
		this.idevent = idevent;
		this.nomevenement = nomevenement;
	}

	public TableEvenements(BigDecimal idevent, String nomevenement, Date datedebut, Date datefin) {
		this.idevent = idevent;
		this.nomevenement = nomevenement;
		this.datedebut = datedebut;
		this.datefin = datefin;
	}

	public BigDecimal getIdevent() {
		return this.idevent;
	}

	public void setIdevent(BigDecimal idevent) {
		this.idevent = idevent;
	}

	public String getNomevenement() {
		return this.nomevenement;
	}

	public void setNomevenement(String nomevenement) {
		this.nomevenement = nomevenement;
	}

	public Date getDatedebut() {
		return this.datedebut;
	}

	public void setDatedebut(Date datedebut) {
		this.datedebut = datedebut;
	}

	public Date getDatefin() {
		return this.datefin;
	}

	public void setDatefin(Date datefin) {
		this.datefin = datefin;
	}

}
