package hibernate.model;
// Generated 20 déc. 2015 18:41:22 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;

/**
 * TableTypesNewsletter generated by hbm2java
 */
import org.hibernate.annotations.DynamicUpdate;
@DynamicUpdate
public class TableTypesNewsletter implements java.io.Serializable {

	private BigDecimal idtypenewsletter;
	private String nomtypenewsletter;

	public TableTypesNewsletter() {
	}

	public TableTypesNewsletter(BigDecimal idtypenewsletter, String nomtypenewsletter) {
		this.idtypenewsletter = idtypenewsletter;
		this.nomtypenewsletter = nomtypenewsletter;
	}

	public BigDecimal getIdtypenewsletter() {
		return this.idtypenewsletter;
	}

	public void setIdtypenewsletter(BigDecimal idtypenewsletter) {
		this.idtypenewsletter = idtypenewsletter;
	}

	public String getNomtypenewsletter() {
		return this.nomtypenewsletter;
	}

	public void setNomtypenewsletter(String nomtypenewsletter) {
		this.nomtypenewsletter = nomtypenewsletter;
	}

}
