package hibernate.model;
// Generated 20 déc. 2015 18:41:22 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;

/**
 * TableTypesContrat generated by hbm2java
 */
import org.hibernate.annotations.DynamicUpdate;
@DynamicUpdate
public class TableTypesContrat implements java.io.Serializable {

	private BigDecimal idtypecontrat;
	private String nomtypecontrat;

	public TableTypesContrat() {
	}

	public TableTypesContrat(BigDecimal idtypecontrat, String nomtypecontrat) {
		this.idtypecontrat = idtypecontrat;
		this.nomtypecontrat = nomtypecontrat;
	}

	public BigDecimal getIdtypecontrat() {
		return this.idtypecontrat;
	}

	public void setIdtypecontrat(BigDecimal idtypecontrat) {
		this.idtypecontrat = idtypecontrat;
	}

	public String getNomtypecontrat() {
		return this.nomtypecontrat;
	}

	public void setNomtypecontrat(String nomtypecontrat) {
		this.nomtypecontrat = nomtypecontrat;
	}

}
