package hibernate.model;
// Generated 20 déc. 2015 18:41:22 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;

/**
 * TableTypesCompetence generated by hbm2java
 */
import org.hibernate.annotations.DynamicUpdate;
@DynamicUpdate
public class TableTypesCompetence implements java.io.Serializable {

	private BigDecimal idtypecompetence;
	private String nomtypecompetence;

	public TableTypesCompetence() {
	}

	public TableTypesCompetence(BigDecimal idtypecompetence, String nomtypecompetence) {
		this.idtypecompetence = idtypecompetence;
		this.nomtypecompetence = nomtypecompetence;
	}

	public BigDecimal getIdtypecompetence() {
		return this.idtypecompetence;
	}

	public void setIdtypecompetence(BigDecimal idtypecompetence) {
		this.idtypecompetence = idtypecompetence;
	}

	public String getNomtypecompetence() {
		return this.nomtypecompetence;
	}

	public void setNomtypecompetence(String nomtypecompetence) {
		this.nomtypecompetence = nomtypecompetence;
	}

}
