package hibernate.model;
// Generated 20 déc. 2015 18:41:22 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;

/**
 * TableSecteur generated by hbm2java
 */
import org.hibernate.annotations.DynamicUpdate;
@DynamicUpdate
public class TableSecteur implements java.io.Serializable {

	private BigDecimal idtypesecteur;
	private String nomsecteur;

	public TableSecteur() {
	}

	public TableSecteur(BigDecimal idtypesecteur, String nomsecteur) {
		this.idtypesecteur = idtypesecteur;
		this.nomsecteur = nomsecteur;
	}

	public BigDecimal getIdtypesecteur() {
		return this.idtypesecteur;
	}

	public void setIdtypesecteur(BigDecimal idtypesecteur) {
		this.idtypesecteur = idtypesecteur;
	}

	public String getNomsecteur() {
		return this.nomsecteur;
	}

	public void setNomsecteur(String nomsecteur) {
		this.nomsecteur = nomsecteur;
	}

}
