package hibernate.model;
// Generated 20 déc. 2015 18:41:22 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;

/**
 * TableMailing generated by hbm2java
 */
import org.hibernate.annotations.DynamicUpdate;
@DynamicUpdate
public class TableMailing implements java.io.Serializable {

	private BigDecimal idliste;
	private BigDecimal idmailinglist;
	private BigDecimal iduser;

	public TableMailing() {
	}

	public TableMailing(BigDecimal idliste, BigDecimal idmailinglist, BigDecimal iduser) {
		this.idliste = idliste;
		this.idmailinglist = idmailinglist;
		this.iduser = iduser;
	}

	public BigDecimal getIdliste() {
		return this.idliste;
	}

	public void setIdliste(BigDecimal idliste) {
		this.idliste = idliste;
	}

	public BigDecimal getIdmailinglist() {
		return this.idmailinglist;
	}

	public void setIdmailinglist(BigDecimal idmailinglist) {
		this.idmailinglist = idmailinglist;
	}

	public BigDecimal getIduser() {
		return this.iduser;
	}

	public void setIduser(BigDecimal iduser) {
		this.iduser = iduser;
	}

}
