package hibernate.model;
// Generated 20 déc. 2015 18:41:22 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;

/**
 * TableNewsletters generated by hbm2java
 */
import org.hibernate.annotations.DynamicUpdate;
@DynamicUpdate
public class TableNewsletters implements java.io.Serializable {

	private BigDecimal idnewsletter;
	private BigDecimal idtypenwesletter;
	private BigDecimal idmailinglist;
	private String bodyhtml;
	private String header;

	public TableNewsletters() {
	}

	public TableNewsletters(BigDecimal idnewsletter, String bodyhtml, String header) {
		this.idnewsletter = idnewsletter;
		this.bodyhtml = bodyhtml;
		this.header = header;
	}

	public TableNewsletters(BigDecimal idnewsletter, BigDecimal idtypenwesletter, BigDecimal idmailinglist,
			String bodyhtml, String header) {
		this.idnewsletter = idnewsletter;
		this.idtypenwesletter = idtypenwesletter;
		this.idmailinglist = idmailinglist;
		this.bodyhtml = bodyhtml;
		this.header = header;
	}

	public BigDecimal getIdnewsletter() {
		return this.idnewsletter;
	}

	public void setIdnewsletter(BigDecimal idnewsletter) {
		this.idnewsletter = idnewsletter;
	}

	public BigDecimal getIdtypenwesletter() {
		return this.idtypenwesletter;
	}

	public void setIdtypenwesletter(BigDecimal idtypenwesletter) {
		this.idtypenwesletter = idtypenwesletter;
	}

	public BigDecimal getIdmailinglist() {
		return this.idmailinglist;
	}

	public void setIdmailinglist(BigDecimal idmailinglist) {
		this.idmailinglist = idmailinglist;
	}

	public String getBodyhtml() {
		return this.bodyhtml;
	}

	public void setBodyhtml(String bodyhtml) {
		this.bodyhtml = bodyhtml;
	}

	public String getHeader() {
		return this.header;
	}

	public void setHeader(String header) {
		this.header = header;
	}

}
