package hibernate.model;
// Generated 20 déc. 2015 18:41:22 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;

/**
 * UserRoleId generated by hbm2java
 */
import org.hibernate.annotations.DynamicUpdate;
@DynamicUpdate
public class UserRole implements java.io.Serializable {

	private BigDecimal iduser;
	private String roles;

	public UserRole() {
	}

	public UserRole(BigDecimal iduser, String roles) {
		this.iduser = iduser;
		this.roles = roles;
	}

	public BigDecimal getIduser() {
		return this.iduser;
	}

	public void setIduser(BigDecimal iduser) {
		this.iduser = iduser;
	}

	public String getRoles() {
		return this.roles;
	}

	public void setRoles(String roles) {
		this.roles = roles;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserRole))
			return false;
		UserRole castOther = (UserRole) other;

		return ((this.getIduser() == castOther.getIduser()) || (this.getIduser() != null
				&& castOther.getIduser() != null && this.getIduser().equals(castOther.getIduser())))
				&& ((this.getRoles() == castOther.getRoles()) || (this.getRoles() != null
						&& castOther.getRoles() != null && this.getRoles().equals(castOther.getRoles())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIduser() == null ? 0 : this.getIduser().hashCode());
		result = 37 * result + (getRoles() == null ? 0 : this.getRoles().hashCode());
		return result;
	}

}