package hibernate.model;
// Generated 28 déc. 2015 16:23:36 by Hibernate Tools 4.0.0.Final

import java.math.BigDecimal;

/**
 * UserRole generated by hbm2java
 */
public class UserRole implements java.io.Serializable {

	private BigDecimal iduserole;
	private BigDecimal iduser;
	private String roles;

	public UserRole() {
	}

	public UserRole(BigDecimal iduserole, BigDecimal iduser, String roles) {
		this.iduserole = iduserole;
		this.iduser = iduser;
		this.roles = roles;
	}

	public BigDecimal getIduserole() {
		return this.iduserole;
	}

	public void setIduserole(BigDecimal iduserole) {
		this.iduserole = iduserole;
	}

	public BigDecimal getIduser() {
		return this.iduser;
	}

	public void setIduser(BigDecimal iduser) {
		this.iduser = iduser;
	}

	public String getRoles() {
		return this.roles;
	}

	public void setRoles(String roles) {
		this.roles = roles;
	}

}
